site_name: Voidrun
theme:
  name: readthedocs 

nav:
  - Get Started:
    - Home: index.md
    - Installation: getstarted/installation.md
  - API Services:
      - One-shot Run: api/oneshot.md
      - Judge with Expectation: api/judge_expected.md
      - Judge with Script: api/judge_scripted.md
      - WebSocket Service: api/websocket_service.md
  - System Design:
      - Project Architecture: systemdesign/project_architecture.md
      - Documentation Structure: systemdesign/documentation_structure.md
