site_name: VoidRun
site_description: Isolated Code Executor
site_author: Mani Ebrahimi
site_url: https://voidrun.dev

repo_name: mani/voidrun
repo_url: https://gitlab.com/mani/voidrun
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: pink
  font:
    text: Roboto
    code: Fira Code

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Components: architecture/components.md
  - API Reference:
      - HTTP Service: api/http.md
      - WebSocket Service: api/websocket.md
  - Guides:
      - Writing Judge Scripts: guides/judge-scripts.md
      - Adding New Language Support: guides/new-language.md
  - FAQ: faq.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/mani/voidrun
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mani/voidrun

