name: Build and Push to Docker Hub on Release

on:
  release:
    types: [published]

env:
  IMAGE_NAME: voidrun
  DOCKER_HUB_USER: maniebra
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set release tag
        id: meta
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$DOCKER_HUB_USER/$IMAGE_NAME:${{ steps.meta.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$DOCKER_HUB_USER/$IMAGE_NAME:${{ steps.meta.outputs.tag }}
